batch_size: 32  # Number of elements in a batch.
# drop_last: true # Whether to drop a batch when there are too few samples to match its size
do_mvn: true
# size_batch_by_length: true
# num_length_buckets: 10
