name: cpc.nocontext
system_description: "CPC with only the convolutions and transformer predictor"
context_type: id
conv:
  output_size: 256
  norm_type: batch
training:
  data:
    common:
      batch_size: 6
      drop_last: true
  cpc_loss:
    prediction_steps: 8
    prediction_type: csa
    offset: 9
  chunking:
    max_chunks: 32
