name: fbank
system_description: "41-dim fbank baseline"
input_size: 41
feat_type: fbank
latent_type: ff
context_type: id
training:
  num_devices: 4
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
  chunking:
    lobe_size: 127
    max_chunks: 16
