name: cpc.trans8-960
system_description: "cpc.trans8 trained on 960h libri data"
context_type: csa
train_part: 960
conv:
  output_size: 256
csa:
  max_width: 8
  dim_feedforward: 1024
training:
  num_devices:
  data:
    common:
      batch_size: 12
      drop_last: true
  cpc_loss:
    prediction_type: csa
    offset: 7
  chunking:
    max_chunks: 64
