name: cpc.csa128
system_description: "CPC-small but with a 128-frame causal transformer layer"
context_type: csa
conv:
  output_size: 256
  norm_type: none
csa:
  max_width: 128
  dim_feedforward: 1024
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 200
  data:
    common:
      batch_size: 4
  cpc_loss:
    prediction_type: csa
  chunking:
    policy: none
