name: cpc.cmono-p8
system_description: "CPC-cmono but with 8 prediction steps"
context_type: csa
conv:
  output_size: 256
  norm_type: channel
csa:
  max_width: 9
training:
  num_devices: 2
  data:
    common:
      batch_size: 6
      drop_last: true
  cpc_loss:
    prediction_steps: 8
    prediction_type: csa
    offset: 8
  chunking:
    max_chunks: 32
