name: bestrq.trans4
system_description: 'BEST-RQ + cpc.trans w/ 4-frame causal context'
feat_type: fbank-80
train_part: '100'
input_size: 80
latent_type: ff
context_type: csa
ff:
  output_size: 256
csa:
  dim_feedforward: 1024
  max_width: 4
training:
  data:
    common:
      batch_size: 12
      drop_last: true
  chunking:
    lobe_size: 127
    max_chunks: 64
  best_rq_loss:
    prediction_type: sa    
