name: cpc.csa8-460
system_description: "cpc.csa8 on 460h clean libri data"
context_type: csa
train_part: "460"
conv:
  output_size: 256
csa:
  max_width: 8
  dim_feedforward: 1024
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 1000
  early_stopping_threshold: 0.01
  data:
    common:
      batch_size: 4
  cpc_loss:
    prediction_type: ff
    prediction_dropout_prob: 0.5
  chunking:
    policy: none
    # lobe_size: 81916
    max_chunks:
