name: fbank
system_description: "41-dim fbank baseline"
input_size: 41
feat_type: fbank
latent_type: id
context_type: id
training:
  num_devices: 1
  data:
    common:
      batch_size: 12
      drop_last: true
  cpc_loss:
    prediction_type: ff
  chunking:
    lobe_size: 127
    max_chunks: 64
