name: cpc.csa8-fbank-80
system_description: "cpc.csa8 w/ conv stack replaced w/ 80-dim f-fbank"
input_size: 80
feat_type: fbank-80
latent_type: ff
context_type: csa
csa:
  max_width: 8
  dim_feedforward: 1024
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 1000
  early_stopping_threshold: 0.01
  data:
    common:
      batch_size: 4
  cpc_loss:
    prediction_type: ff
    prediction_dropout_prob: 0.5
  chunking:
    policy: none
    # lobe_size: 81916
    max_chunks:
