name: cpc.tri
system_description: "CPC.trans but with approx. 3 phonemes' context"
context_type: csa
conv:
  output_size: 256
  norm_type: batch
csa:
  max_width: 11 # ~43 / 4
  num_layers: 4
training:
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
    offset: 42
  chunking:
    max_chunks: 16
