name: cpc.mono
system_description: "CPC.trans but with approx. 1 phoneme's context"
context_type: csa
conv:
  output_size: 256
  norm_type: batch
csa:
  max_width: 5  # ~19 / 4
  num_layers: 4
training:
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
    offset: 18
  chunking:
    max_chunks: 16
