name: bestrq.trans
system_description: BEST-RQ + cpc.trans
feat_type: fbank-80
train_part: '100'
input_size: 80
latent_type: ff
context_type: csa
ff:
  output_size: 256
csa:
  dim_feedforward: 1024
  max_width: 128
training:
  data:
    prefer_split: false
    common:
      batch_size: 12
      drop_last: true
  chunking:
    lobe_size: 127
    max_chunks: 64
  best_rq_loss:
    prediction_type: sa    
