name: cpc.small
system_description: "CPC-small network"
conv:
  output_size: 256
  norm_type: batch
recur:
  num_layers: 2
  recurrent_type: lstm
training:
  num_devices: 1
  data:
    common:
      batch_size: 12
      drop_last: true
  cpc_loss:
    prediction_type: csa
    gutted_steps: 11
  chunking:
    max_chunks: 64
