name: cpc.trans
system_description: "CPC-small but with transfomers"
context_type: csa
conv:
  output_size: 256
  norm_type: channel
csa:
  max_width: 128
training:
  num_devices: 4
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
  chunking:
    max_chunks: 16
