name: cpc.trans64
system_description: "CPC-small but with transfomers and 64-frame window"
context_type: csa
conv:
  output_size: 256
csa:
  max_width: 64
  dim_feedforward: 1024
training:
  num_devices:
  data:
    common:
      batch_size: 12
      drop_last: true
  cpc_loss:
    prediction_type: csa
    offset: 63
  chunking:
    max_chunks: 64
