name: bestrq.small
system_description: "BEST-RQ network w/ context network resembling CTC-small"
input_size: 80
feat_type: fbank-80
latent_type: ff
recur:
  num_layers: 2
  recurrent_type: lstm
training:
  num_devices: 4
  data:
    common:
      batch_size: 3
      drop_last: true
  loss_type: best-rq
  best_rq_loss:
    prediction_type: sa
  chunking:
    lobe_size: 127
    max_chunks: 16
