name: bestrq.small
system_description: BEST-RQ + cpc.small
input_size: 80
feat_type: fbank-80
latent_type: ff
recur:
  num_layers: 4
  recurrent_type: lstm
training:
  num_devices: 2
  data:
    common:
      batch_size: 6
      drop_last: true
  loss_type: best-rq
  best_rq_loss:
    prediction_type: sa
  chunking:
    lobe_size: 127
    max_chunks: 32
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 1000
  early_stopping_threshold: 0.01
  data:
    common:
      batch_size: 4
  loss-type: best-rq
  best_rq_loss:
    prediction_type: ff
  chunking:
    policy: none
    # lobe_size: 81916
    max_chunks:
