name: bestrq.csa
system_description: "BEST-RQ with a causal transformer layer"
feat_type: fbank-80
input_size: 80
latent_type: ff
context_type: csa
ff:
  output_size: 256
csa:
  dim_feedforward: 1024
  max_width:
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 200
  data:
    common:
      batch_size: 4
  loss_type: best-rq
  best_rq_loss:
    prediction_type: csa
    mask_width: 12
  chunking:
    policy: none
