name: cpc.trans
system_description: "CPC-small but with transfomers"
context_type: csa
conv:
  output_size: 256
  norm_type: batch
csa:
  max_width: 128
  num_layers: 4
training:
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
  chunking:
    max_chunks: 16
