name: cpc.csa
system_description: "CPC-small but with a causal transformer layer"
context_type: csa
conv:
  output_size: 256
  norm_type: channel
csa:
  max_width:
  dim_feedforward: 1024
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 1000
  early_stopping_threshold: 0.01
  data:
    common:
      batch_size: 4
  cpc_loss:
    prediction_type: ff
    prediction_dropout_prob: 0.5
  chunking:
    policy: none
    # lobe_size: 81916
    max_chunks:
