name: cpc.csa8
system_description: "CPC-small but with an 8-frame causal transformer layer"
context_type: csa
conv:
  output_size: 256
  norm_type: channel
csa:
  max_width: 8
  dim_feedforward: 1024
training:
  num_devices:
  accumulate_grad_batches: 3
  max_epochs: 1000
  data:
    common:
      batch_size: 4
  cpc_loss:
    prediction_type: ff
    prediction_dropout_prob: 0.0
  chunking:
    policy: none
    # lobe_size: 81916
    max_chunks:
