name: cpc.trans8
system_description: "CPC-small but with transfomers and 8-frame window"
context_type: csa
conv:
  output_size: 256
csa:
  max_width: 8
  num_layers: 2
  dim_feedforward: 512
training:
  num_devices:
  data:
    common:
      batch_size: 12
      drop_last: true
  cpc_loss:
    prediction_type: csa
    offset: 14
  chunking:
    max_chunks: 64
