name: cpc.cmono-p8
system_description: "CPC-cmono but with 8 prediction steps"
context_type: csa
conv:
  output_size: 256
  norm_type: batch
csa:
  max_width: 2  # ~9 / 4
  num_layers: 4
training:
  data:
    common:
      batch_size: 6
      drop_last: true
  cpc_loss:
    prediction_steps: 8
    prediction_type: csa
    offset: 9
  chunking:
    max_chunks: 32
