name: fbank-p12
system_description: "41-dim fbank baseline w/ 12 CPC prediction steps"
input_size: 41
latent_type: ff
context_type: id
training:
  data:
    common:
      batch_size: 3
      drop_last: true
  cpc_loss:
    prediction_type: csa
  chunking:
    lobe_size: 127
    max_chunks: 16
