name: scpc-s3prl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - editdistance
  - filelock
  - numpy >=1.21
  - omegaconf >=2.1.1
  - pip
  - pytorch 1.13.1
  - pytorch::pytorch-cuda 11.6
  - pyyaml >=5.4.1
  - requests
  - ruamel.yaml
  - setuptools 59.5.0
  - tensorboardx
  - torchaudio 0.13.1
  - tqdm >=4.56.0
  - transformers
