name: scpc-s3prl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - torchaudio >=0.8.0
  - pytorch >=1.8.0,!=1.10.0
  - tqdm >=4.56.0
  - numpy >=1.21
  - pyyaml >=5.4.1
  - filelock
  - omegaconf >=2.1.1
  - setuptools 59.5.0
  - requests
  - transformers
  - pip
  - pip:
    - './s3prl'
